name: Events exercices

on:
  push:
    branches:
      - main
    paths:
      - '**.ts'
      - 'node_modules/**'

  pull_request:
    types:
      - opened
      - closed

  # schedule:
  #   - cron: '*/5 * * * *'
  #   - cron: '*/30 */1 * * *'
  #   - cron: '0 3 * * 2'

      
jobs:
  exo-mr-job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Say hello from job1
        run: echo "Hello ${{ github.actor }} from job1"

  exo-mr-job2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Say hello from job2
        run: echo "Hello ${{ github.actor }} from job2"

