name: Events exercices push

on:
  push:
    branches:
      - 'dev'
  pull_request:
    types:
      - opened
      - closed

jobs:
  exo-mr-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Echo hello world
        run: echo "Hello world"