name: Events exercices push

on:
  push:
    paths:
      - '**.ts'


jobs:
  exo-push-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "Hello ${{ github.actor }}"