name: Events exercices push

on:
  push:
    branches:
      - 'dev'
  pull_request:
    types:
      - opened
      - closed
    paths:
      - '**.ts'
      - 'node_modules/**'
      
jobs:
  exo-mr-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "Hello ${{ github.actor }}"