name: Events exercices push

on:
  push:
    branches:
      - main
    paths:
      - '**.ts'
      - 'node_modules/**'

  # schedule:
  #   - cron: '*/5 * * * *'
  #   - cron: '*/30 */1 * * *'
  #   - cron: '0 3 * * 2'


jobs:
  exo-push-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "Hello ${{ github.actor }}"